name: Check with Gradle

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 1.11
              uses: actions/setup-java@v2
              with:
                  distribution: temurin
                  java-version: 11
                  cache: gradle

            - name: Check with Gradle
              run: ./gradlew check --no-daemon

            - name: Run automated test with Gradle
              run: ./gradlew simulateJavaDebug -PautomatedTest=true --no-daemon
